import { HostId } from "../schema/index.js";
import type { Adapter, CapabilityLevel, HostCapabilities } from "./types.js";

const ROWS: { key: keyof HostCapabilities; label: string }[] = [
  { key: "instructions", label: "Project instructions (AGENTS.md)" },
  { key: "hierarchicalInstructions", label: "Hierarchical / scoped instructions" },
  { key: "skills", label: "Agent Skills (SKILL.md)" },
  { key: "roleSubagents", label: "Role subagents + dispatch" },
  { key: "perRoleToolRestriction", label: "Per-role tool restriction" },
  { key: "gates", label: "Hooks / Approved? gate" },
  { key: "mcp", label: "MCP" },
  { key: "pluginDistribution", label: "Plugin distribution metadata" },
  { key: "lspGuidance", label: "LSP setup guidance" },
];

const LEVEL_LABEL: Record<CapabilityLevel, string> = {
  native: "Native",
  partial: "Partial",
  fallback: "Fallback",
  none: "None",
};

const HOST_ORDER = HostId.options;

function sortAdapters(adapters: Adapter[]): Adapter[] {
  return [...adapters].sort((a, b) => HOST_ORDER.indexOf(a.host) - HOST_ORDER.indexOf(b.host));
}

/**
 * Render the cross-host capability matrix from the adapters' declared
 * capabilities. Generated (not hand-maintained) so it can never drift from the
 * adapter code; U4 commits the output to `docs/capability-matrix.md` and a test
 * asserts the file matches this render.
 */
export function renderCapabilityMatrix(adapters: Adapter[]): string {
  const sorted = sortAdapters(adapters);
  const header = `| Capability | ${sorted.map((a) => a.host).join(" | ")} |`;
  const divider = `|---|${sorted.map(() => "---").join("|")}|`;
  const rows = ROWS.map((row) => {
    const cells = sorted.map((a) => LEVEL_LABEL[a.capabilities[row.key]]);
    return `| ${row.label} | ${cells.join(" | ")} |`;
  });

  return [
    "# Cross-host capability matrix",
    "",
    "<!-- GENERATED by `aisdlc gen-matrix` from adapter capability declarations. Do not edit by hand. -->",
    "",
    "Levels: **Native** (first-class), **Partial** (supported with limits),",
    "**Fallback** (degraded path — see `portability.gap.yml`), **None**.",
    "",
    header,
    divider,
    ...rows,
    "",
  ].join("\n");
}
