import type { HostId } from "../schema/index.js";
import type { EmittedFile, Gap } from "./types.js";

export const HOST_SETUP_GUIDE_PATH = ".sdlc/host-setup.md";

interface HostGuide {
  title: string;
  artifacts: string[];
  activation: string[];
  caveats?: string[];
}

const HOST_GUIDES: Record<HostId, HostGuide> = {
  cursor: {
    title: "Cursor",
    artifacts: [
      "AGENTS.md",
      ".cursor/agents/",
      ".cursor/skills/",
      ".agents/skills/",
      ".cursor/hooks.json",
      ".cursor/hooks/",
      ".cursor/mcp.json",
      ".cursor/permissions.json",
      ".cursor/sdlc/role-policy.json",
      ".cursor-plugin/plugin.json",
    ],
    activation: [
      "Open the repository in Cursor so workspace agents, skills, hooks, MCP, and AGENTS.md are discovered from the project.",
      "If `.cursor-plugin/plugin.json` exists, use it as plugin distribution metadata; the in-repo files remain the source of truth.",
      "Review MCP server definitions before enabling external systems.",
    ],
    caveats: [
      "Cursor's MCP allowlist is global; per-role MCP least privilege is enforced by the generated hook and role policy.",
    ],
  },
  "claude-code": {
    title: "Claude Code",
    artifacts: [
      "CLAUDE.md",
      "AGENTS.md",
      ".claude/agents/",
      ".claude/skills/",
      ".claude/settings.json",
      ".claude/hooks/",
      ".mcp.json",
    ],
    activation: [
      "Start Claude Code from the repository root so root project settings, hooks, skills, agents, MCP, and CLAUDE.md are loaded.",
      "Trust the workspace when prompted before relying on project-local skills, hooks, or MCP.",
      "Use `/reload-plugins` or restart the session after changing plugin-like Claude Code components.",
    ],
  },
  copilot: {
    title: "GitHub Copilot",
    artifacts: [
      "AGENTS.md",
      ".github/copilot-instructions.md",
      ".github/agents/",
      ".github/skills/",
      ".github/hooks/",
      ".github/workflows/sdlc-gate.yml",
      ".vscode/mcp.json",
    ],
    activation: [
      "Open the repository or workspace folder in a Copilot-enabled IDE so instructions, agents, skills, and MCP settings are discovered.",
      "For Copilot CLI or cloud agent, keep `.github/hooks/*.json` committed so hook configuration is loaded from the cloned repository.",
      "Require the generated `SDLC Gate` workflow through branch protection when Copilot IDE is used.",
    ],
    caveats: [
      "Copilot IDE does not provide a fail-closed pre-tool hook, so Approved? degrades to instructions plus CLI/cloud hooks plus CI.",
      "Per-role MCP reach is declared in custom-agent tools but remains partial in IDE surfaces.",
    ],
  },
  codex: {
    title: "Codex",
    artifacts: [
      "AGENTS.md",
      ".agents/skills/",
      ".codex/agents/",
      ".codex/skills/",
      ".codex/config.toml",
      ".codex/hooks/",
      ".codex/sdlc/role-policy.json",
    ],
    activation: [
      "Start Codex from a trusted project root so project `.codex/config.toml`, hooks, agents, skills, MCP, and AGENTS.md are loaded.",
      "Review project trust prompts before allowing hooks or MCP servers to run.",
      "Restart Codex or reload configuration after changing project-local `.codex/` files.",
    ],
  },
};

export function renderHostSetupGuide(hosts: HostId[], files: EmittedFile[], gaps: Gap[]): string {
  const emitted = new Set(files.map((file) => file.path));
  const sections = hosts.map((host) => renderHostSection(host, emitted, gaps));
  return [
    "# AI SDLC Host Setup",
    "",
    "Generated by `aisdlc compile`. This guide explains how each enabled host discovers the emitted project-local configuration. It is activation guidance, not proof that a live IDE or CLI has loaded the files.",
    "",
    ...sections,
  ].join("\n");
}

function renderHostSection(host: HostId, emitted: Set<string>, gaps: Gap[]): string {
  const guide = HOST_GUIDES[host];
  const hostGaps = gaps.filter((gap) => gap.host === host);
  const artifactLines = guide.artifacts.map((artifact) =>
    emitted.has(artifact) || hasPathUnder(emitted, artifact)
      ? `- \`${artifact}\``
      : `- \`${artifact}\` (conditional or not emitted in this configuration)`,
  );
  const lines = [`## ${guide.title}`, "", "### Native Artifacts", "", ...artifactLines, ""];
  lines.push("### Activation", "", ...guide.activation.map((step) => `- ${step}`), "");
  if (guide.caveats?.length || hostGaps.length) {
    lines.push("### Caveats", "");
    for (const caveat of guide.caveats ?? []) lines.push(`- ${caveat}`);
    for (const gap of hostGaps) lines.push(`- ${gap.capability}: ${gap.reason}`);
    lines.push("");
  }
  return lines.join("\n");
}

function hasPathUnder(emitted: Set<string>, prefix: string): boolean {
  if (!prefix.endsWith("/")) return false;
  for (const path of emitted) {
    if (path.startsWith(prefix)) return true;
  }
  return false;
}
