/**
 * The structured, host-neutral context the customize phase mines about a repo's
 * shape and hands to the compiler: per-package instruction bodies, a navigable
 * codebase map, and the directories agents should not search. It is persisted as
 * `project-context.json` beside the overlay and re-loaded at compile time so the
 * adapters can emit per-package instruction files, a codebase map, and
 * host-native exclusion rules without re-mining.
 */

/** One row of the codebase map: where a thing lives and what it is. */
export interface MapEntry {
  /** Repo-relative POSIX path of the package or module. */
  path: string;
  /** A short, evidence-backed description (e.g. `TypeScript, tests via \`vitest run\``). */
  role: string;
  /** Repo paths that justify the entry. */
  sources: string[];
}

export type InstructionScopeKind = "package" | "module";

export type InstructionScopeOwnership = "generated" | "accepted-merge";

/** Marker written into generated instruction hierarchy files for overwrite safety. */
export const GENERATED_INSTRUCTION_MARKER =
  "<!-- Generated by ai-sdlc instruction hierarchy. Do not edit directly. -->";

/** A host-neutral instruction scope accepted by customize and compiled by adapters. */
export interface InstructionScope {
  /** Repo-relative POSIX path of the local guidance scope. */
  path: string;
  /** Why the scope exists. */
  kind: InstructionScopeKind;
  /** Short evidence-backed role for the area. */
  role: string;
  /** Repo paths that justify this scope. */
  sources: string[];
  /** Host-neutral markdown body emitted into native host surfaces. */
  instructionBody: string;
  /** Host target descriptors used for review/status surfaces. */
  hostTargets: string[];
  /** Whether this scope is generated-only or includes accepted user/LLM policy. */
  ownership: InstructionScopeOwnership;
  /** Compile emits only accepted scopes. Deterministic mined scopes are accepted immediately. */
  accepted: boolean;
}

/** Reviewable instruction hierarchy produced by customize and consumed by compile. */
export interface InstructionHierarchy {
  version: 1;
  scopes: InstructionScope[];
}

/** Pre-rendered per-package instruction content for a single workspace package. */
export interface PackageContext {
  /** Repo-relative POSIX path of the package directory. */
  path: string;
  /** Mined language identifiers for this package. */
  languages?: string[];
  /** The rendered instruction-file body (host-neutral markdown). */
  instructionBody: string;
  /** The package-local test command, when known. */
  testCommand?: string;
}

export interface ProjectContext {
  /** Mined language identifiers across the repository. */
  languages?: string[];
  packages: PackageContext[];
  /** Accepted instruction scopes. Present for customize runs that support hierarchy emission. */
  instructionHierarchy?: InstructionHierarchy;
  map: MapEntry[];
  /** Directory names agents should not search/read (vendored, generated, caches). */
  exclusions: string[];
}

/**
 * Static fallback exclusion set, emitted when no mined ProjectContext is present
 * (e.g. `compile` run without a prior `customize`). Mirrors the vendored/
 * generated/cache directories `repo-miner` ignores, minus `.git`. Sorted so
 * emitted host config is byte-stable.
 */
export const DEFAULT_EXCLUSIONS: string[] = [
  ".mypy_cache",
  ".next",
  ".pytest_cache",
  ".ruff_cache",
  ".sdlc",
  ".tox",
  ".venv",
  "__pycache__",
  "build",
  "coverage",
  "dist",
  "env",
  "node_modules",
  "venv",
];

/** Render the codebase map as a markdown section appended to the constitution. */
export function renderCodebaseMap(map: MapEntry[]): string {
  const lines = [
    "## Codebase map",
    "",
    "Where things live in this repo (compiled from repo evidence). Use it to",
    "navigate directly instead of scanning the whole tree.",
    "",
  ];
  for (const entry of map) {
    const src = entry.sources.length > 0 ? ` _(${entry.sources.join(", ")})_` : "";
    lines.push(`- \`${entry.path}\` — ${entry.role}.${src}`);
  }
  return lines.join("\n");
}

export function acceptedInstructionScopes(ctx: ProjectContext | undefined): InstructionScope[] {
  if (ctx?.instructionHierarchy) {
    const scopes = ctx.instructionHierarchy.scopes.filter(
      (scope) => scope.accepted && scope.path !== ".",
    );
    if (scopes.length > 0 || ctx.instructionHierarchy.scopes.length > 0) return scopes;
  }
  return (ctx?.packages ?? []).map((pkg) => ({
    path: pkg.path,
    kind: "package",
    role: packageRoleFromContext(pkg),
    sources: [pkg.path],
    instructionBody: pkg.instructionBody,
    hostTargets: hostTargetsForScope(pkg.path),
    ownership: "generated",
    accepted: true,
  }));
}

export function hostTargetsForScope(path: string): string[] {
  const slug = slugifyScopePath(path);
  return [
    `${path}/CLAUDE.md`,
    `${path}/AGENTS.md`,
    `.cursor/rules/${slug}.mdc`,
    `.github/instructions/${slug}.instructions.md`,
  ];
}

export function scopeApplyGlob(path: string): string {
  return `${path}/**`;
}

export function slugifyScopePath(path: string): string {
  return path
    .split(/[/\\]+/)
    .filter((segment) => segment.length > 0)
    .map((segment) =>
      [...segment]
        .map((char) => (/[a-zA-Z0-9.]/.test(char) ? char : `_${char.charCodeAt(0).toString(16)}_`))
        .join(""),
    )
    .join("-");
}

/** Serialize a ProjectContext for persistence (stable, trailing newline). */
export function serializeProjectContext(ctx: ProjectContext): string {
  return `${JSON.stringify(ctx, null, 2)}\n`;
}

/** Serialize an InstructionHierarchy for reviewable persistence. */
export function serializeInstructionHierarchy(hierarchy: InstructionHierarchy): string {
  return `${JSON.stringify(hierarchy, null, 2)}\n`;
}

/** Parse a persisted ProjectContext, returning `undefined` on malformed input. */
export function parseProjectContext(text: string): ProjectContext | undefined {
  try {
    const parsed = JSON.parse(text) as Partial<ProjectContext>;
    if (
      parsed &&
      Array.isArray(parsed.packages) &&
      Array.isArray(parsed.map) &&
      Array.isArray(parsed.exclusions)
    ) {
      return {
        languages: Array.isArray(parsed.languages) ? parsed.languages : undefined,
        packages: parsed.packages,
        instructionHierarchy: parseInstructionHierarchy(parsed.instructionHierarchy),
        map: parsed.map,
        exclusions: parsed.exclusions,
      };
    }
  } catch {
    /* malformed → treat as absent */
  }
  return undefined;
}

export function parseInstructionHierarchy(value: unknown): InstructionHierarchy | undefined {
  if (!value || typeof value !== "object") return undefined;
  const candidate = value as Partial<InstructionHierarchy>;
  if (candidate.version !== 1 || !Array.isArray(candidate.scopes)) return undefined;
  const scopes = candidate.scopes.filter(isInstructionScope);
  if (scopes.length !== candidate.scopes.length) return undefined;
  return { version: 1, scopes };
}

function isInstructionScope(value: unknown): value is InstructionScope {
  if (!value || typeof value !== "object") return false;
  const candidate = value as Partial<InstructionScope>;
  return (
    typeof candidate.path === "string" &&
    (candidate.kind === "package" || candidate.kind === "module") &&
    typeof candidate.role === "string" &&
    Array.isArray(candidate.sources) &&
    candidate.sources.every((source) => typeof source === "string") &&
    typeof candidate.instructionBody === "string" &&
    Array.isArray(candidate.hostTargets) &&
    candidate.hostTargets.every((target) => typeof target === "string") &&
    (candidate.ownership === "generated" || candidate.ownership === "accepted-merge") &&
    typeof candidate.accepted === "boolean"
  );
}

function packageRoleFromContext(pkg: PackageContext): string {
  const lang = pkg.languages?.[0] ?? "Package";
  const test = pkg.testCommand ? `, tests via \`${pkg.testCommand}\`` : "";
  return `${capitalize(lang)}${test}`;
}

function capitalize(s: string): string {
  return s.length === 0 ? s : s[0]!.toUpperCase() + s.slice(1);
}
