import type { EmittedFile, NeutralModel } from "../../core/types.js";
import { buildRolePolicy, stableJson } from "../shared/roles.js";
import { joinTomlSections } from "./toml.js";
import { renderMcpSections } from "./mcp.js";

const MCP_GATE_SCRIPT = `#!/usr/bin/env node
// Codex PreToolUse MCP gate: deny MCP calls a role is not permitted to make.
import { readFileSync } from "node:fs";

function readStdin() {
  try { return JSON.parse(readFileSync(0, "utf8")); } catch { return {}; }
}

function serverFromToolName(toolName) {
  if (typeof toolName !== "string" || !toolName.startsWith("mcp__")) return "";
  const parts = toolName.split("__");
  return parts.length >= 2 ? parts[1] : "";
}

const input = readStdin();
const role = input.agent_type ?? process.env.SDLC_ACTIVE_ROLE ?? "";
const server = serverFromToolName(input.tool_name);

let policy = {};
try { policy = JSON.parse(readFileSync(".codex/sdlc/role-policy.json", "utf8")); } catch {}

const hasPolicy = Object.keys(policy).length > 0;
if (server && hasPolicy) {
  const entry = policy[role];
  if (!entry || !entry.servers.includes(server)) {
    console.error(\`SDLC gate: role '\${role || "(unset)"}' may not call MCP server '\${server}'.\`);
    process.exit(2);
  }
}
process.exit(0);
`;

const APPROVED_GATE_SCRIPT = `#!/usr/bin/env node
// Codex PreToolUse Approved? gate. Blocks apply_patch/Bash/MCP until SDLC_APPROVED=1.
import { execSync } from "node:child_process";

const approved = process.env.SDLC_APPROVED === "1";

if (!approved) {
  console.error("SDLC gate: changes are not Approved? yet. Halting before write/MCP.");
  process.exit(2);
}

// Record the approval event to loop trace history.
const taskId = process.env.SDLC_TASK_ID || "unknown";
const scope = process.env.SDLC_SCOPE || "workspace";
const role = process.env.SDLC_ACTIVE_ROLE || "unknown";

const event = JSON.stringify({
  type: "approval_gate",
  taskId,
  verdict: "approved",
  role,
  reason: "Human approved via SDLC_APPROVED=1",
  evidence: scope ? [scope] : undefined,
});

try {
  // Use double quotes and escape backslashes and double quotes in the JSON
  const escapedEvent = event.replace(/\\\\/g, "\\\\\\\\").replace(/"/g, '\\\\"');
  execSync(\`npx --yes aisdlc record-event --event "\${escapedEvent}"\`, { stdio: "ignore" });
} catch (err) {
  // Best-effort: log recording failures but don't block the gate.
  console.warn("Warning: failed to record approval event:", err.message);
}

process.exit(0);
`;

const HOOK_HEADER = `# Generated by ai-sdlc. Re-compile from the base + overlay to update.

[features]
hooks = true

[agents]
max_threads = 6
max_depth = 1
`;

function renderHookSections(): string[] {
  return [
    `[[hooks.PreToolUse]]
matcher = "apply_patch|Bash|mcp__.*"

[[hooks.PreToolUse.hooks]]
type = "command"
command = "node ./.codex/hooks/approved-gate.mjs"
statusMessage = "Checking Approved? gate"`,
    `[[hooks.PreToolUse]]
matcher = "mcp__.*"

[[hooks.PreToolUse.hooks]]
type = "command"
command = "node ./.codex/hooks/mcp-gate.mjs"
statusMessage = "Checking MCP least-privilege"`,
  ];
}

/** Merge MCP tables, hook tables, and feature flags into `.codex/config.toml`. */
export function renderCodexConfig(model: NeutralModel): string {
  return joinTomlSections([HOOK_HEADER.trim(), ...renderMcpSections(model), ...renderHookSections()]);
}

/**
 * Codex gate: `PreToolUse` hooks in `.codex/config.toml` plus runtime scripts.
 * Per-role MCP policy is consumed by the MCP hook script.
 */
export function emitGates(model: NeutralModel): EmittedFile[] {
  return [
    { path: ".codex/config.toml", contents: renderCodexConfig(model) },
    { path: ".codex/sdlc/role-policy.json", contents: stableJson(buildRolePolicy(model)) },
    { path: ".codex/hooks/mcp-gate.mjs", contents: MCP_GATE_SCRIPT },
    { path: ".codex/hooks/approved-gate.mjs", contents: APPROVED_GATE_SCRIPT },
  ];
}
