import { describe, expect, it } from "vitest";
import { ClaudeCodeAdapter } from "../../src/adapters/claude-code/index.js";
import { CodexAdapter } from "../../src/adapters/codex/index.js";
import { CopilotAdapter } from "../../src/adapters/copilot/index.js";
import { CursorAdapter } from "../../src/adapters/cursor/index.js";
import type { ProjectContext } from "../../src/core/project-context.js";
import { makeModel } from "../helpers/model.js";

function byPath(files: { path: string; contents: string }[]): Map<string, string> {
  return new Map(files.map((f) => [f.path, f.contents]));
}

describe("instructions emit", () => {
  it("cursor emits AGENTS.md as a passthrough of the constitution", () => {
    const model = makeModel();
    const files = byPath(new CursorAdapter().emit(model).files);
    expect(files.get("AGENTS.md")).toBe(model.constitution);
  });

  it("claude emits CLAUDE.md with an @AGENTS.md import and a Claude appendix", () => {
    const model = makeModel();
    const files = byPath(new ClaudeCodeAdapter().emit(model).files);
    expect(files.has("AGENTS.md")).toBe(true);
    const claude = files.get("CLAUDE.md")!;
    expect(claude).toContain("@AGENTS.md");
    expect(claude).toContain("Claude Code appendix");
  });

  it("copilot emits AGENTS.md plus a copilot-instructions excerpt of the gates", () => {
    const model = makeModel();
    const files = byPath(new CopilotAdapter().emit(model).files);
    expect(files.has("AGENTS.md")).toBe(true);
    const excerpt = files.get(".github/copilot-instructions.md")!;
    expect(excerpt).toContain("Non-negotiable gates");
    expect(excerpt).toContain("Review required.");
  });

  it("copilot inlines mined project standards (Copilot does not follow @import reliably)", () => {
    const model = makeModel({
      constitution: [
        makeModel().constitution,
        "",
        "## Project standards (from overlay)",
        "",
        "- Run tests with `pytest`; the test suite must pass before a change ships.",
        "- Lint/format with ruff.",
      ].join("\n"),
    });
    const excerpt = byPath(new CopilotAdapter().emit(model).files).get(
      ".github/copilot-instructions.md",
    )!;
    expect(excerpt).toContain("Project standards");
    expect(excerpt).toContain("pytest");
    expect(excerpt).toContain("ruff");
  });

  it("copilot omits the standards section when the overlay contributes none", () => {
    const excerpt = byPath(new CopilotAdapter().emit(makeModel()).files).get(
      ".github/copilot-instructions.md",
    )!;
    expect(excerpt).not.toContain("Project standards");
  });

  it("codex emits AGENTS.md as a passthrough of the constitution", () => {
    const model = makeModel();
    const files = byPath(new CodexAdapter().emit(model).files);
    expect(files.get("AGENTS.md")).toBe(model.constitution);
  });

  it("emits accepted hierarchy scopes in each host's native instruction surface", () => {
    const model = makeModel({ projectContext: hierarchyContext() });

    const claude = byPath(new ClaudeCodeAdapter().emit(model).files);
    expect(claude.get("src/core/CLAUDE.md")).toContain("local module guidance");

    const codex = byPath(new CodexAdapter().emit(model).files);
    expect(codex.get("src/core/AGENTS.md")).toContain("Role: Source module.");

    const cursor = byPath(new CursorAdapter().emit(model).files);
    expect(cursor.get("src/core/AGENTS.md")).toContain("local module guidance");
    const cursorRule = cursor.get(".cursor/rules/src-core.mdc")!;
    expect(cursorRule).toContain("globs: src/core/**");
    expect(cursorRule).toContain("alwaysApply: false");
    expect(cursorRule).toContain("Follow `src/core/AGENTS.md`");
    expect(cursorRule).toContain("Generated by ai-sdlc instruction hierarchy");

    const copilot = byPath(new CopilotAdapter().emit(model).files);
    expect(copilot.get(".github/instructions/src-core.instructions.md")).toContain(
      "applyTo: src/core/**",
    );
  });

  it("does not emit nested files for unaccepted or root hierarchy scopes", () => {
    const context = hierarchyContext();
    const baseScope = context.instructionHierarchy!.scopes[0]!;
    context.instructionHierarchy!.scopes = [
      { ...baseScope, accepted: false },
      { ...baseScope, path: ".", hostTargets: [] },
    ];
    const model = makeModel({ projectContext: context });

    const paths = [
      ...new ClaudeCodeAdapter().emit(model).files,
      ...new CodexAdapter().emit(model).files,
      ...new CursorAdapter().emit(model).files,
      ...new CopilotAdapter().emit(model).files,
    ].map((file) => file.path);

    expect(paths).not.toContain("src/core/CLAUDE.md");
    expect(paths).not.toContain("src/core/AGENTS.md");
    expect(paths).not.toContain(".cursor/rules/src-core.mdc");
    expect(paths).not.toContain(".github/instructions/src-core.instructions.md");
  });
});

function hierarchyContext(): ProjectContext {
  const body = [
    "<!-- Generated by ai-sdlc instruction hierarchy. Do not edit directly. -->",
    "",
    "# `src/core` — local module guidance",
    "",
    "Role: Source module.",
    "",
    "## Local standards",
    "",
    "- Keep core host-neutral.",
    "",
  ].join("\n");
  return {
    packages: [],
    map: [{ path: "src/core", role: "Source module", sources: ["src/core"] }],
    exclusions: [],
    instructionHierarchy: {
      version: 1,
      scopes: [
        {
          path: "src/core",
          kind: "module",
          role: "Source module",
          sources: ["src/core"],
          instructionBody: body,
          hostTargets: [
            "src/core/CLAUDE.md",
            "src/core/AGENTS.md",
            ".cursor/rules/src-core.mdc",
            ".github/instructions/src-core.instructions.md",
          ],
          ownership: "generated",
          accepted: true,
        },
      ],
    },
  };
}
